spring.application.name=KLTN
server.port=${PORT:8081}
#tao tien to cho tat ca cac api
spring.mvc.servlet.path=/api
kltn.frontend.url=http://localhost:5173
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
spring.mvc.log-resolved-exception=true
